apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pc
spec:
  selector:
      matchLabels:
        run: frontend-pc
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend-pc
    spec:
      containers:
      - name: frontend-pc-1
        image: pchahal24/pc-frontend:2022-03-07
        imagePullPolicy: Always
        ports:
          - name: port-3000
            containerPort: 3000
            protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
