apiVersion: v1
kind: Service
metadata:
  name: frontend-pc-service
  namespace: pc
  labels:
    app: frontend-pc
spec:
  ports:
  - port: 80
    protocol: TCP
    name: port-5000
    targetPort: 5000
  selector:
    run: frontend-pc
  type: ClusterIP